[package]
name = "up2date"
version = "0.7.0"
authors = ["Ricky Nelson <rickyn@zolmok.com>"]
edition = "2021"

[dependencies]
irust = "1.67.4"
scuttle = { git = "https://github.com/Zolmok/scuttle", tag="v0.4.0" }
sys-info = "0.9"
