[package]
name = "up2date"
version = "0.2.0"
authors = ["Ricky Nelson <rickyn@zolmok.com>"]
edition = "2018"

[dependencies]
scuttle = { git = "https://github.com/Zolmok/scuttle", branch="main" }
sys-info = "0.9"
